language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: ca1WsBfQJhS0sXDU/H/LkUzNxZa5kQE/z8mYpHR4z/qpmJ65QdJAWkVcV3azy/UOhoIJiW3Z3Q6OYmtLZTmQzKJZ5lgpY+L+CUL2ciBTW/x9YlKXqH0P/iKfuAoO2n8FynYU2qFgDaccpUbWuCaGU6nhgqv7hl/LBphRKpnpbaIE0AoAhc7iFbKsypj/QGSG0CKJB73gmgltxTCzzzNvXWQIdMxaBICLjV5B3OcYgifjjRnqtkasKtn0B4CW6wq/V38Sw2vS3lUtJRukpgnoAiUtdG412nuUimeFoM8FYb2rmqusaBqY+FAnT6bIxYBkIAY7LpmfOL2sGuqd1b4JuvsM9aUEK91Vi27Y87cH6nMwuB9JOYINt2pvleD/Gv5PUOR6xGXVuvwD+fCxllwLtFEOVXBaVVpbQk/9ay9vK9hFF0ckEwM0zWwsZ9el45D9JCKJBNsWySVVxtLDbssOEjNedS6+psL/wkNqcDuZLQG7iDjkw5KgBERt/2j0mtplDubxOtOV3AKy/P5aedvMcSnYivs8kFRPTi/3gnufWznxQ7Y+sb2mJ6NewysUiLkcdWnoKoP9b5bxUU8urvh0mxK1uvaXDXDpy7RIww+781Oexe7C7Cqu4ERzYOw1gzxTeIoz7zcgt9HBc8FhPsJuuws8DIRza37jRudaeBA61oE=
